// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKs8Gj8bLUSkorPRuUGVw1A08DJjpSTjE',
    appId: '1:611577907913:web:049b5eac8867545d065b18',
    messagingSenderId: '611577907913',
    projectId: 'household-account-book-de2c4',
    authDomain: 'household-account-book-de2c4.firebaseapp.com',
    storageBucket: 'household-account-book-de2c4.firebasestorage.app',
    measurementId: 'G-MWLSYBY236',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdowrCCjymbkgP4ndc8nM4UHDlXtU5jXI',
    appId: '1:611577907913:android:878416b682f0b276065b18',
    messagingSenderId: '611577907913',
    projectId: 'household-account-book-de2c4',
    storageBucket: 'household-account-book-de2c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb5lYj3ZSOcBMxXus2IBUs2kXhmc9ih38',
    appId: '1:611577907913:ios:7fd353e17a57b35a065b18',
    messagingSenderId: '611577907913',
    projectId: 'household-account-book-de2c4',
    storageBucket: 'household-account-book-de2c4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb5lYj3ZSOcBMxXus2IBUs2kXhmc9ih38',
    appId: '1:611577907913:ios:7fd353e17a57b35a065b18',
    messagingSenderId: '611577907913',
    projectId: 'household-account-book-de2c4',
    storageBucket: 'household-account-book-de2c4.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKs8Gj8bLUSkorPRuUGVw1A08DJjpSTjE',
    appId: '1:611577907913:web:52e5ddff5568a77b065b18',
    messagingSenderId: '611577907913',
    projectId: 'household-account-book-de2c4',
    authDomain: 'household-account-book-de2c4.firebaseapp.com',
    storageBucket: 'household-account-book-de2c4.firebasestorage.app',
    measurementId: 'G-ZM3CRVTCEQ',
  );
}
